apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-alerts
    receivers:
      - uid: telegram_receiver
        type: telegram
        settings:
          bottoken: ${TELEGRAM_BOT_TOKEN}
          chatid: ${GRAFANA_ALERT_CHAT_ID}
